
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pos_data               #jdbc:mysql://52.44.116.58:3306/pos_data?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: Ckddnjs12!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update        #create (시작할때 create한다.   update drop안함
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: true

# org.hibernate.type: trace #??? ?? 2.x, hibernate5

logging:
    pattern:
        level:
            org.springframework.boot: DEBUG
            org.hibernate.SQL: debug
            org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

